In [2]:
import numpy as np

class Layer_Dense:

    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [3]:
# create some data — 3 samples, 4 features
X = np.array([
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
])

# create layer: expects 4 inputs, has 5 neurons
layer1 = Layer_Dense(4, 5)

# forward pass
layer1.forward(X)

print(layer1.output.shape)  # (3, 5)
print(layer1.output)

(3, 5)
[[-0.08157125  0.02014828  0.02071979  0.083958   -0.07381464]
 [-0.06408184  0.00307109  0.0625998   0.09772688 -0.06030818]
 [-0.04399855  0.00360748  0.0289783   0.05306382 -0.07156306]]


In [5]:
""" X:              (3, 4)
layer1.weights: (4, 5)
dot result:     (3, 5)
layer1.biases:  (1, 5)
layer1.output:  (3, 5) """

' X:              (3, 4)\nlayer1.weights: (4, 5)\ndot result:     (3, 5)\nlayer1.biases:  (1, 5)\nlayer1.output:  (3, 5) '

In [6]:
layer1 = Layer_Dense(4, 5)   # 4 inputs → 5 neurons
layer2 = Layer_Dense(5, 2)   # 5 inputs → 2 neurons

layer1.forward(X)
layer2.forward(layer1.output)  # output of layer1 becomes input of layer2

print(layer2.output.shape)  # (3, 2)

(3, 2)


In [7]:
""" Full Shape Visualization 
Raw Data X:      (3, 4)
      ↓
Layer 1 Dense:   weights(4,5)  → output (3, 5)
      ↓
Layer 2 Dense:   weights(5,2)  → output (3, 2)
      ↓
Final output:    (3, 2)  → 3 samples, 2 class scores """


' Full Shape Visualization \nRaw Data X:      (3, 4)\n      ↓\nLayer 1 Dense:   weights(4,5)  → output (3, 5)\n      ↓\nLayer 2 Dense:   weights(5,2)  → output (3, 2)\n      ↓\nFinal output:    (3, 2)  → 3 samples, 2 class scores '

In [8]:
layer1 = Layer_Dense(3, 6)
layer2 = Layer_Dense(6, 4)
layer3 = Layer_Dense(4, 1)

X = np.random.randn(10, 3)

layer1.forward(X)
layer2.forward(layer1.output)
layer3.forward(layer2.output)