In [6]:
import numpy as np

layer_outputs = [4.8, 1.21, 2.385]
# For each value in a vector, calculate the exponential value
exp_values = np.exp(layer_outputs)
print('exponentiated values:\n ')
print(exp_values)

exponentiated values:
 
[121.51041752   3.35348465  10.85906266]


In [10]:
# Now normalize values
norm_values = exp_values / np.sum(exp_values)
print('normalized exponentiated values:\n',norm_values)

normalized exponentiated values:
 [0.89528266 0.02470831 0.08000903]


In [11]:
print('sum of normalized values:\n', np.sum(norm_values))

sum of normalized values:
 0.9999999999999999


# MULTIDIMESIONAL ARRAY OR MATRIX

In [13]:
import numpy as np
layer_outputs = np.array([[4.8, 1.21, 2.385],
                            [8.9, -1.81, 0.2],
                            [1.41, 1.051, 0.026]])
print('Sum without axis')
print(np.sum(layer_outputs))
print('This will be identical to the above since default is None:')
print(np.sum(layer_outputs, axis=None))

Sum without axis
18.172
This will be identical to the above since default is None:
18.172


In [14]:
print('Another way to think of it w/ a matrix == axis 0: columns:')
print(np.sum(layer_outputs, axis=0))

Another way to think of it w/ a matrix == axis 0: columns:
[15.11   0.451  2.611]


# we want to sum the rows instead, like this w/ raw

In [15]:
for i in layer_outputs:
    print(sum(i))

8.395
7.29
2.4869999999999997
